### PR TITLE
fix(types): missing command and result

### PR DESCRIPTION
**Pull request by bodinsamuel**
- add missing types for command and result
- noticed the release reverted my prev package.json changes, was it intentional? https://github.com/samdenty/console-feed/commit/824af1505e756d212f15ad4049cf7df26bf6df07

### CODE REVIEW

**Comment by samdenty** [comment]
> was it intentional
Yep, the build was failing with them. The types are somehow broken

**Comment by bodinsamuel** [comment]
> Yep, the build was failing with them. The types are somehow broken

Ah let me take a look

**Comment by bodinsamuel** [comment]
using `allowSyntheticDefaultImports` seems to do the trick, lmk

**Comment by bodinsamuel** [comment]
Hey @samdenty can I have some review on this please? ☺️

**Comment by samdenty** [comment]
the demo seems to be broken with the `import *` stuff, see browser logs w/ `yarn start`.

**Comment by samdenty** [comment]
awesome! published as 3.2.2

**Comment by bodinsamuel** [comment]
thank you 🙏🏻

**Pull request merged**
